version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Maintain dependencies for npm and yarn
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: monthly

  # Maintain dependencies for npm and yarn
  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly